//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data;



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://TygaSoft.WCFService", ConfigurationName="IPDAOrder")]
public interface IPDAOrder
{
    
    // CODEGEN: 参数“HelloWordResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
    [System.ServiceModel.OperationContractAttribute(Action="http://TygaSoft.WCFService/IPDAOrder/HelloWord", ReplyAction="http://TygaSoft.WCFService/IPDAOrder/HelloWordResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    HelloWordResponse HelloWord(HelloWordRequest request);
    
    // CODEGEN: 参数“InsertResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
    [System.ServiceModel.OperationContractAttribute(Action="http://TygaSoft.WCFService/IPDAOrder/Insert", ReplyAction="http://TygaSoft.WCFService/IPDAOrder/InsertResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    InsertResponse Insert(InsertRequest request);
    
    // CODEGEN: 参数“InsertByBatchResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
    [System.ServiceModel.OperationContractAttribute(Action="http://TygaSoft.WCFService/IPDAOrder/InsertByBatch", ReplyAction="http://TygaSoft.WCFService/IPDAOrder/InsertByBatchResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    InsertByBatchResponse InsertByBatch(InsertByBatchRequest request);
    
    // CODEGEN: 参数“GetAllUsersResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlArrayAttribute”。
    [System.ServiceModel.OperationContractAttribute(Action="http://TygaSoft.WCFService/IPDAOrder/GetAllUsers", ReplyAction="http://TygaSoft.WCFService/IPDAOrder/GetAllUsersResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    GetAllUsersResponse GetAllUsers(GetAllUsersRequest request);
    
    // CODEGEN: 参数“ValidateUserResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
    [System.ServiceModel.OperationContractAttribute(Action="http://TygaSoft.WCFService/IPDAOrder/ValidateUser", ReplyAction="http://TygaSoft.WCFService/IPDAOrder/ValidateUserResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    ValidateUserResponse ValidateUser(ValidateUserRequest request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="HelloWord", WrapperNamespace="http://TygaSoft.WCFService", IsWrapped=true)]
public partial class HelloWordRequest
{
    
    public HelloWordRequest()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="HelloWordResponse", WrapperNamespace="http://TygaSoft.WCFService", IsWrapped=true)]
public partial class HelloWordResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://TygaSoft.WCFService", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string HelloWordResult;
    
    public HelloWordResponse()
    {
    }
    
    public HelloWordResponse(string HelloWordResult)
    {
        this.HelloWordResult = HelloWordResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="Insert", WrapperNamespace="http://TygaSoft.WCFService", IsWrapped=true)]
public partial class InsertRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://TygaSoft.WCFService", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string opType;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://TygaSoft.WCFService", Order=1)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string barCode;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://TygaSoft.WCFService", Order=2)]
    public System.DateTime scanTime;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://TygaSoft.WCFService", Order=3)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string userName;
    
    public InsertRequest()
    {
    }
    
    public InsertRequest(string opType, string barCode, System.DateTime scanTime, string userName)
    {
        this.opType = opType;
        this.barCode = barCode;
        this.scanTime = scanTime;
        this.userName = userName;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="InsertResponse", WrapperNamespace="http://TygaSoft.WCFService", IsWrapped=true)]
public partial class InsertResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://TygaSoft.WCFService", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string InsertResult;
    
    public InsertResponse()
    {
    }
    
    public InsertResponse(string InsertResult)
    {
        this.InsertResult = InsertResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="InsertByBatch", WrapperNamespace="http://TygaSoft.WCFService", IsWrapped=true)]
public partial class InsertByBatchRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://TygaSoft.WCFService", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Data.DataTable dt;
    
    public InsertByBatchRequest()
    {
    }
    
    public InsertByBatchRequest(System.Data.DataTable dt)
    {
        this.dt = dt;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="InsertByBatchResponse", WrapperNamespace="http://TygaSoft.WCFService", IsWrapped=true)]
public partial class InsertByBatchResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://TygaSoft.WCFService", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string InsertByBatchResult;
    
    public InsertByBatchResponse()
    {
    }
    
    public InsertByBatchResponse(string InsertByBatchResult)
    {
        this.InsertByBatchResult = InsertByBatchResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetAllUsers", WrapperNamespace="http://TygaSoft.WCFService", IsWrapped=true)]
public partial class GetAllUsersRequest
{
    
    public GetAllUsersRequest()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetAllUsersResponse", WrapperNamespace="http://TygaSoft.WCFService", IsWrapped=true)]
public partial class GetAllUsersResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://TygaSoft.WCFService", Order=0)]
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
    public string[] GetAllUsersResult;
    
    public GetAllUsersResponse()
    {
    }
    
    public GetAllUsersResponse(string[] GetAllUsersResult)
    {
        this.GetAllUsersResult = GetAllUsersResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="ValidateUser", WrapperNamespace="http://TygaSoft.WCFService", IsWrapped=true)]
public partial class ValidateUserRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://TygaSoft.WCFService", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string username;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://TygaSoft.WCFService", Order=1)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string password;
    
    public ValidateUserRequest()
    {
    }
    
    public ValidateUserRequest(string username, string password)
    {
        this.username = username;
        this.password = password;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="ValidateUserResponse", WrapperNamespace="http://TygaSoft.WCFService", IsWrapped=true)]
public partial class ValidateUserResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://TygaSoft.WCFService", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ValidateUserResult;
    
    public ValidateUserResponse()
    {
    }
    
    public ValidateUserResponse(string ValidateUserResult)
    {
        this.ValidateUserResult = ValidateUserResult;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IPDAOrderChannel : IPDAOrder, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class PDAOrderClient : System.ServiceModel.ClientBase<IPDAOrder>, IPDAOrder
{
    
    public PDAOrderClient()
    {
    }
    
    public PDAOrderClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public PDAOrderClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public PDAOrderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public PDAOrderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    HelloWordResponse IPDAOrder.HelloWord(HelloWordRequest request)
    {
        return base.Channel.HelloWord(request);
    }
    
    public string HelloWord()
    {
        HelloWordRequest inValue = new HelloWordRequest();
        HelloWordResponse retVal = ((IPDAOrder)(this)).HelloWord(inValue);
        return retVal.HelloWordResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    InsertResponse IPDAOrder.Insert(InsertRequest request)
    {
        return base.Channel.Insert(request);
    }
    
    public string Insert(string opType, string barCode, System.DateTime scanTime, string userName)
    {
        InsertRequest inValue = new InsertRequest();
        inValue.opType = opType;
        inValue.barCode = barCode;
        inValue.scanTime = scanTime;
        inValue.userName = userName;
        InsertResponse retVal = ((IPDAOrder)(this)).Insert(inValue);
        return retVal.InsertResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    InsertByBatchResponse IPDAOrder.InsertByBatch(InsertByBatchRequest request)
    {
        return base.Channel.InsertByBatch(request);
    }
    
    public string InsertByBatch(System.Data.DataTable dt)
    {
        InsertByBatchRequest inValue = new InsertByBatchRequest();
        inValue.dt = dt;
        InsertByBatchResponse retVal = ((IPDAOrder)(this)).InsertByBatch(inValue);
        return retVal.InsertByBatchResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetAllUsersResponse IPDAOrder.GetAllUsers(GetAllUsersRequest request)
    {
        return base.Channel.GetAllUsers(request);
    }
    
    public string[] GetAllUsers()
    {
        GetAllUsersRequest inValue = new GetAllUsersRequest();
        GetAllUsersResponse retVal = ((IPDAOrder)(this)).GetAllUsers(inValue);
        return retVal.GetAllUsersResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    ValidateUserResponse IPDAOrder.ValidateUser(ValidateUserRequest request)
    {
        return base.Channel.ValidateUser(request);
    }
    
    public string ValidateUser(string username, string password)
    {
        ValidateUserRequest inValue = new ValidateUserRequest();
        inValue.username = username;
        inValue.password = password;
        ValidateUserResponse retVal = ((IPDAOrder)(this)).ValidateUser(inValue);
        return retVal.ValidateUserResult;
    }
}
